name = "SimplePlanarGraphs"
uuid = "4800dc9b-61c6-46c3-b3ee-487f8393015d"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.0"

[deps]
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Triangle = "56f361f5-126b-55db-87fb-1c71988fcde4"

[compat]
julia = "1"
SimpleGraphs = "0.5, 0.6, 0.7"
Triangle = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
